## 서울시 생필품 농수축산물 가격 정보 데이터 EDA

In [3]:
pip install chardet

Collecting chardet
  Downloading chardet-5.2.0-py3-none-any.whl.metadata (3.4 kB)
Downloading chardet-5.2.0-py3-none-any.whl (199 kB)
Installing collected packages: chardet
Successfully installed chardet-5.2.0
Note: you may need to restart the kernel to use updated packages.

In [4]:
import chardet

# 파일 인코딩 확인
with open("data_2023.csv", "rb") as f:
    result = chardet.detect(f.read())
print(result["encoding"])  # 감지된 인코딩 확인

# 감지된 인코딩으로 파일 읽기
data = pd.read_csv("data_2023.csv", encoding=result["encoding"])

EUC-KR

In [5]:
data.head()

,일련번호,시장/마트 번호,시장/마트 이름,품목 번호,품목 이름,실판매규격,가격(원),년도-월,비고,시장유형 구분(시장/마트) 코드,시장유형 구분(시장/마트) 이름,자치구 코드,자치구 이름,점검일자
0,297326,270,성대전통시장,70,어묵 300g,NaN,0,2023-01,NaN,1,전통시장,590000,동작구,2023-01-23
1,297349,270,성대전통시장,27,파프리카 200g,NaN,1180,2023-01,NaN,1,전통시장,590000,동작구,2023-01-23
2,297348,270,성대전통시장,65,통조림(참치) 150g,NaN,0,2023-01,NaN,1,전통시장,590000,동작구,2023-01-23
3,297347,270,성대전통시장,24,토마토 1kg,NaN,8650,2023-01,NaN,1,전통시장,590000,동작구,2023-01-23
4,297346,270,성대전통시장,21,콩나물 500g,NaN,1000,2023-01,NaN,1,전통시장,590000,동작구,2023-01-23

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76559 entries, 0 to 76558
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   일련번호               76559 non-null  int64
 1   시장/마트 번호           76559 non-null  int64
 2   시장/마트 이름           76559 non-null  object
 3   품목 번호              76559 non-null  int64
 4   품목 이름              76365 non-null  object
 5   실판매규격              0 non-null      float64
 6   가격(원)              76559 non-null  int64
 7   년도-월               76559 non-null  object
 8   비고                 9995 non-null   object
 9   시장유형 구분(시장/마트) 코드  76559 non-null  int64
 10  시장유형 구분(시장/마트) 이름  76559 non-null  object
 11  자치구 코드             76559 non-null  int64
 12  자치구 이름             76559 non-null  object
 13  점검일자               76559 non-null  object
dtypes: float64(1), int64(6), object(7)
memory usage: 8.2+ MB

In [7]:
data.describe(include='all')

,일련번호,시장/마트 번호,시장/마트 이름,품목 번호,품목 이름,실판매규격,가격(원),년도-월,비고,시장유형 구분(시장/마트) 코드,시장유형 구분(시장/마트) 이름,자치구 코드,자치구 이름,점검일자
count,76559.000000,76559.000000,76559,76559.000000,76365,0.0,76559.000000,76559,9995,76559.0,76559,76559.000000,76559,76559
unique,NaN,NaN,100,NaN,113,NaN,NaN,11,5695,NaN,1,NaN,25,81
top,NaN,NaN,성대전통시장,NaN,감자 1kg,NaN,NaN,2023-06,할인,NaN,전통시장,NaN,관악구,2023-06-29
freq,NaN,NaN,949,NaN,969,NaN,NaN,8041,217,NaN,76559,NaN,4358,3552
mean,160560.286681,182.304158,NaN,45.172338,NaN,NaN,4404.434449,NaN,NaN,1.0,NaN,416672.500947,NaN,NaN
std,85102.888351,89.851596,NaN,26.268420,NaN,NaN,8612.408427,NaN,NaN,0.0,NaN,187365.992922,NaN,NaN
min,1319.000000,1.000000,NaN,1.000000,NaN,NaN,0.000000,NaN,NaN,1.0,NaN,110000.000000,NaN,NaN
25%,85710.500000,103.000000,NaN,23.000000,NaN,NaN,0.000000,NaN,NaN,1.0,NaN,260000.000000,NaN,NaN
50%,169372.000000,232.000000,NaN,44.000000,NaN,NaN,2500.000000,NaN,NaN,1.0,NaN,410000.000000,NaN,NaN
75%,231171.500000,256.000000,NaN,66.000000,NaN,NaN,5000.000000,NaN,NaN,1.0,NaN,560000.000000,NaN,NaN
max,325179.000000,283.000000,NaN,105.000000,NaN,NaN,214100.000000,NaN,NaN,1.0,NaN,740000.000000,NaN,NaN

In [14]:
# 컬럼별 고유값 확인
columns_to_check = [
    "시장/마트 이름",
    "품목 번호",
    "품목 이름",
    "실판매규격",
    "시장유형 구분(시장/마트) 코드",
    "시장유형 구분(시장/마트) 이름",
    "자치구 코드",
    "자치구 이름",
]

print("\n컬럼별 고유값:")
for col in columns_to_check:
    if col in data.columns:
        unique_values = data[col].unique()
        print(f"- {col}: {len(unique_values)} unique values")
        print(unique_values)
        print()
    else:
        print(f"- {col}: 해당 컬럼이 데이터에 없습니다.")

컬럼별 고유값:
- 시장/마트 이름: 100 unique values
['성대전통시장' '창신골목시장' '백학시장' '성동용답상가시장' '행당시장상점가' '사가정시장' '쌍문시장' '마포·공덕시장'
 '오목교중앙시장' '목사랑시장(목4동시장)' '남부골목시장' '구로시장' '강남개포시장' '영동전통시장' '도곡시장' '신중앙시장'
 '용문시장' '화양제일골목시장' '중곡제일골목시장' '우림시장' '중랑동부시장' '정릉시장' '대림시장' '영천시장' '까치산시장'
 '가리봉시장' '남성역골목시장' '상도전통시장' '양재시장' '마천중앙시장' '광장시장' '통인시장' '서울중앙시장'
 '약수시장 골목형 상가' '후암시장' '뚝도시장' '금남시장' '답십리현대시장' '답십리시장' '청량리종합시장' '장위전통시장'
 '백년시장' '솔샘시장' '방학동도깨비시장' '연서시장' '증산종합시장' '목동깨비시장(목3동시장)' '남구로시장' '고척근린시장'
 '남문시장' '대명여울빛거리시장' '은행나무시장' '남성시장' '미성동도깨비시장' '신림중앙시장' '남부종합시장' '남대문시장'
 '이촌종합시장' '노룬산골목시장' '자양골목시장' '경동시장' '동원시장' '돌곶이시장' '돈암제일시장' '숭인시장'
 '수유재래시장' '장미원골목시장' '창동골목시장' '신창시장' '상계중앙시장' '공릉동 도깨비시장' '대조시장' '백련시장'
 '포방터시장' '인왕시장' '망원시장' '마포농수산물시장' '신영시장' '송화(벽화)시장' '화곡본동시장' '비단길현대시장'
 '영일시장' '영등포전통시장' '대신시장' '대림중앙시장' '관악중부시장' '관악신사시장(신림4동)' '신원시장(신림1동)'
 '인헌시장' '청담삼익시장' '새마을시장' '풍납시장' '방이시장' '고분다리전통시장' '둔촌역전통시장' '만리시장' '아현시장'
 '우리시장' '암사종합시장' '길동복조리시장']

- 품목 번호: 100 unique values
[ 70  27  65  24  21  30  88  53  62  82  59  81   9  56  97  66  38  43
 104  74  40  17   8  93  15  91  18   1  52  55  29  10  75  67  34  33
  51  83  77  98 100  44  16  79   2  64  80  96  58  57  90   4  23  13
   3  84  12  71  92  14  39 101  76  69  63  54  45  61  11  68  48  35
  94  25  32  36  89 105 102  31  26   7  50 103  95  49  42  19  99  37
  20  41  47  46  60  72  28   5   6  78]

- 품목 이름: 114 unique values
['어묵 300g' '파프리카 200g' '통조림(참치) 150g' '토마토 1kg ' '콩나물 500g' '콩 1kg'
 '콜라 1.5L(1병)' '케찹 500g' '컵라면 1개' '칫솔 4입 1개' '치즈 400g' '치약 160g 1개'
 '참외 1개' '참기름 320ml' '쪽파 1kg' '즉석밥 210g 3개입' '조기 1마리' '조개(바지락) 1kg'
 '전복 5마리' '우유 1L' '오징어 1마리' '오이(다다기) 1개' '오렌지 1개' '열무 1kg' '양파 1망'
 '양배추 1포기' '애호박 1개' '쌀 20kg 1포' '식초 1.8L' '식용유 1.8L' '시금치 1단' '수박 1통'
 '소주 360ml, 1병' '소시지 1kg' '소고기(수입) 100g' '소고기(국산) 100g' '설탕 1kg'
 '샴푸 680ml 1통' '생수 500ml 1병' '생강 1kg' '새우젓 1kg' '새우(흰다리새우) 1kg' '상추 100g'
 '사이다 1.5L 1병' '사과 1개' '빵 3개입' '비누 4개입 1개' '브로콜리(국산) 1개' '분유 800g'
 '부침가루 1kg' '부추 1단' '복숭아 1개' '버섯(새송이버섯) 100g' '배추 1포기' '배(신고) 1개'
 '바디워시 1000ml 1개' '바나나 1송이' '밀가루 1kg' '미나리 100g' '무 1개' '명태 1마리'
 '멸치액젓 1kg' '맥주 500ml 1캔' '맛김 16팩' '만두 1800g' '마요네즈 500g' '마른멸치 100g'
 '라면 5개입 1봉' '딸기 100g' '두부 380g' '된장 1kg' '돼지고기 100g' '도라지 100g' '대파 1kg'
 '당근 1kg' '닭고기 1kg' '단감 1개(200g)' '낙지 1마리' '꽃게(암게) 1kg' '깻잎 100g'
 '깐마늘 1kg' '귤 10개' '굵은소금(천일염) 1kg' '굴 1kg' '가지 1개' '간장 1통' '갈치 1마리'
 '감자 1kg' '갓 1kg' '계란 10개' '고구마 1kg' '고등어 1마리' '고추장 1kg' '고춧가루(국산) 1kg'
 '국수 900g' '햄 340g' '풋고추 100g' '포도(샤인머스켓) 1kg' nan '호박 1개' '새우 1kg'
 '파 1단(대파 1kg)' '콜라 1.8L(1병)' '포도 1kg' '배 1개' '버섯 100g' '소금 1봉' '오이 1개'
 '조개 1kg' '고춧가루 1kg' '파프리카 100g' '마늘 1kg' '대파 1단' '감 10개']

- 실판매규격: 1 unique values
[nan]

- 시장유형 구분(시장/마트) 코드: 1 unique values
[1]

- 시장유형 구분(시장/마트) 이름: 1 unique values
['전통시장']

- 자치구 코드: 25 unique values
[590000 110000 140000 200000 260000 320000 440000 470000 500000 530000
 680000 170000 215000 290000 380000 410000 650000 710000 230000 305000
 545000 620000 350000 560000 740000]

- 자치구 이름: 25 unique values
['동작구' '종로구' '중구' '성동구' '중랑구' '도봉구' '마포구' '양천구' '강서구' '구로구' '강남구' '용산구'
 '광진구' '성북구' '은평구' '서대문구' '서초구' '송파구' '동대문구' '강북구' '금천구' '관악구' '노원구'
 '영등포구' '강동구']

'실판매규격', '시장유형 구분(시장/마트) 코드', '시장유형 구분(시장/마트) 이름'은 무의미함!

### 학교 주변 추출

In [15]:
near_univ = data[data["자치구 이름"].isin(["서대문구", "은평구", "마포구"])]
not_near_univ = data[~data["자치구 이름"].isin(["서대문구", "은평구", "마포구"])] ## 필요 X

In [16]:
columns_to_check_2 = [
    "시장/마트 이름",
    "자치구 이름",
]

print("\n컬럼별 고유값:")
for col in columns_to_check:
    if col in near_univ.columns:
        unique_values = near_univ[col].unique()
        print(f"- {col}: {len(unique_values)} unique values")
        print(unique_values)
        print()
    else:
        print(f"- {col}: 해당 컬럼이 데이터에 없습니다.")

컬럼별 고유값:
- 시장/마트 이름: 12 unique values
['마포·공덕시장' '대림시장' '영천시장' '연서시장' '증산종합시장' '대조시장' '백련시장' '포방터시장' '인왕시장'
 '망원시장' '마포농수산물시장' '아현시장']

- 품목 번호: 98 unique values
[ 49  29  10  75  50  33  51  77  44  16  79   2  64  57  23  13   3  12
  71  14  39  76  54  45  61  11  48  47  41  20  19  42  35  32  36  89
  31  46  18  28  25  65  24  21  30  62   9  56  38  74  17  15   1  52
  55  84  34  70   8  40  43  59  53  72  27  37  60  80  69  88  68  67
  66  83  82  63  58  81   5   4  26   7  95  99 103 102 105  94  90  96
 100  98  91  93 104  97  92 101]

- 품목 이름: 111 unique values
['간장 1통' '빵 3개입' nan '굵은소금(천일염) 1kg' '버섯 100g' '배추 1포기' '새우(흰다리새우) 1kg'
 '바나나 1송이' '사과 1개' '무 1개' '명태 1마리' '버섯(새송이버섯) 100g' '배(신고) 1개' '마요네즈 500g'
 '마른멸치 100g' '라면 5개입 1봉' '딸기 100g' '된장 1kg' '돼지고기 100g' '당근 1kg' '닭고기 1kg'
 '고등어 1마리' '고구마 1kg' '감자 1kg' '갈치 1마리' '단감 1개(200g)' '깻잎 100g' '고춧가루 1kg'
 '고춧가루(국산) 1kg' '애호박 1개' '식초 1.8L' '대파 1kg' '시금치 1단' '수박 1통'
 '소주 360ml, 1병' '소금 1봉' '소고기(국산) 100g' '설탕 1kg' '오이(다다기) 1개' '새우 1kg'
 '쌀 20kg 1포' '사이다 1.5L 1병' '식용유 1.8L' '바디워시 1000ml 1개' '양파 1망' '어묵 300g'
 '오이 1개' '오징어 1마리' '조개(바지락) 1kg' '조개 1kg' '조기 1마리' '참기름 320ml' '참외 1개'
 '치즈 400g' '컵라면 1개' '케찹 500g' '콩 1kg' '토마토 1kg ' '풋고추 100g' '파프리카 100g'
 '파프리카 200g' '계란 10개' '국수 900g' '맥주 500ml 1캔' '밀가루 1kg' '배 1개' '부침가루 1kg'
 '비누 4개입 1개' '생수 500ml 1병' '고추장 1kg' '맛김 16팩' '우유 1L' '콜라 1.5L(1병)'
 '콜라 1.8L(1병)' '오렌지 1개' '햄 340g' '두부 380g' '소시지 1kg' '즉석밥 210g 3개입'
 '통조림(참치) 150g' '만두 1800g' '치약 160g 1개' '분유 800g' '칫솔 4입 1개' '포도 1kg'
 '포도(샤인머스켓) 1kg' '소고기(수입) 100g' '마늘 1kg' '깐마늘 1kg' '콩나물 500g' '호박 1개'
 '귤 10개' '샴푸 680ml 1통' '복숭아 1개' '상추 100g' '가지 1개' '갓 1kg' '굴 1kg'
 '꽃게(암게) 1kg' '낙지 1마리' '도라지 100g' '부추 1단' '브로콜리(국산) 1개' '새우젓 1kg' '생강 1kg'
 '양배추 1포기' '열무 1kg' '전복 5마리' '쪽파 1kg' '미나리 100g' '멸치액젓 1kg']

- 실판매규격: 1 unique values
[nan]

- 시장유형 구분(시장/마트) 코드: 1 unique values
[1]

- 시장유형 구분(시장/마트) 이름: 1 unique values
['전통시장']

- 자치구 코드: 3 unique values
[440000 380000 410000]

- 자치구 이름: 3 unique values
['마포구' '은평구' '서대문구']

'마포·공덕시장' '대림시장' '영천시장' '연서시장' '증산종합시장' '대조시장' '백련시장' '포방터시장' '인왕시장' '망원시장' '마포농수산물시장' '아현시장' 중에서 학교 근처에 있는 시장인 '백련시장' '망원시장' '마포농수산물시장' '대림시장' '증산종합시장'만 사용

In [17]:
near_markets = data[data["시장/마트 이름"].isin(["백련시장", "망원시장", "마포농수산물시장", "대림시장", "증산종합시장"])]

In [18]:
# 품목별 가격 평균 계산
avg_price = near_markets.groupby(["품목 번호", "품목 이름"])["가격(원)"].mean().reset_index()
avg_price.rename(columns={"가격(원)": "평균 가격(원)"}, inplace=True)
avg_price

     품목 번호          품목 이름      평균 가격(원)
0        1      쌀 20kg 1포  35761.111111
1        2          사과 1개   2076.282051
2        3       배(신고) 1개   3254.642857
3        4         복숭아 1개   1054.210526
4        5  포도(샤인머스켓) 1kg   5944.634146
..     ...            ...           ...
113    101       멸치액젓 1kg   7050.000000
114    102     꽃게(암게) 1kg  14375.000000
115    103          굴 1kg  22166.700000
116    104         전복 5마리   7416.000000
117    105         낙지 1마리   4814.777778

[118 rows x 3 columns]

###  서울시 전체와 평균 가격 비교 (위의 시장들도 포함 - 전체 흐름 파악이 목적이니까)

In [19]:
avg_price_tot = data.groupby(["품목 번호", "품목 이름"])["가격(원)"].mean().reset_index()
avg_price_tot.rename(columns={"가격(원)": "평균 가격(원)"}, inplace=True)
avg_price_tot

     품목 번호       품목 이름      평균 가격(원)
0        1   쌀 20kg 1포  49661.580928
1        2       사과 1개   2473.600675
2        3    배(신고) 1개   3546.306080
3        4        배 1개      0.000000
4        4      배추 1포기      0.000000
..     ...         ...           ...
576    101    멸치액젓 1kg   6311.494737
577    102  꽃게(암게) 1kg  12827.064516
578    103       굴 1kg  21780.606218
579    104      전복 5마리   9096.957447
580    105      낙지 1마리   4090.925926

[581 rows x 3 columns]

In [20]:
# natural join
merged_data = pd.merge(avg_price, avg_price_tot, on=["품목 번호", "품목 이름"], suffixes=('_market', '_total'))

# 'cheaper' 컬럼 추가
merged_data['cheaper'] = (merged_data["평균 가격(원)_market"] < merged_data["평균 가격(원)_total"]).astype(int)

# '가격 차이(원)'과 '가격 차이(%)' 계산
merged_data['가격 차이(원)'] = merged_data["평균 가격(원)_total"] - merged_data["평균 가격(원)_market"]
merged_data['가격 차이(%)'] = (merged_data['가격 차이(원)'] / merged_data["평균 가격(원)_total"]) * 100

print(merged_data)

     품목 번호          품목 이름  평균 가격(원)_market  평균 가격(원)_total  cheaper  \
0        1      쌀 20kg 1포     35761.111111    49661.580928        1
1        2          사과 1개      2076.282051     2473.600675        1
2        3       배(신고) 1개      3254.642857     3546.306080        1
3        4         복숭아 1개      1054.210526     1355.932203        1
4        5  포도(샤인머스켓) 1kg      5944.634146     5849.881637        0
..     ...            ...              ...             ...      ...
113    101       멸치액젓 1kg      7050.000000     6311.494737        0
114    102     꽃게(암게) 1kg     14375.000000    12827.064516        0
115    103          굴 1kg     22166.700000    21780.606218        0
116    104         전복 5마리      7416.000000     9096.957447        1
117    105         낙지 1마리      4814.777778     4090.925926        0

         가격 차이(원)   가격 차이(%)
0    13900.469817  27.990389
1      397.318624  16.062359
2      291.663223   8.224423
3      301.721677  22.251974
4      -94.752509  -1.619734
..            ...        ...
113   -738.505263 -11.700957
114  -1547.935484 -12.067730
115   -386.093782  -1.772649
116   1680.957447  18.478238
117   -723.851852 -17.694084

[118 rows x 7 columns]

In [21]:
merged_data['cheaper'].value_counts()

cheaper
1    79
0    39
Name: count, dtype: int64

학교 주변 시장이 서울시 평균보다 더 싼 물건의 종류가 많다

In [22]:
print(merged_data['가격 차이(원)'].mean())
print(merged_data['가격 차이(%)'].mean())

284.97755830113874
9.329100936688647

서울시 시장 물가보다 학교 주변 시장 물가가 약 284원 정도 싸고, 9.32% 정도 싸다

### 학교 주변 시장끼리 물가 비교

### 카테고리 그룹화
- 농산물: 채소, 과일, 곡물 등
- 축산물: 돼지고기, 소고기, 닭고기 등
- 생선/해산물: 조개, 새우, 오징어, 갈치 등
- 생필품: 비누, 샴푸, 칫솔, 치약 등
- 인스턴트: 라면, 즉석밥, 통조림 등
- 음료: 콜라, 사이다, 우유, 소주 등

In [33]:
# 품목별 카테고리 지정
def assign_category(item):
    if isinstance(item, str):  # item이 문자열인지 확인
        for category, items in categories.items():
            if any(item.startswith(it) for it in items):
                return category
    return "기타"  # 지정되지 않은 항목 또는 NaN

if 'near_markets' in locals() and 'seoul_avg_data' in locals():  # 서울시 평균 데이터가 있어야 함
    # 카테고리 추가
    near_markets["품목 카테고리"] = near_markets["품목 이름"].apply(assign_category)
    seoul_avg_data["품목 카테고리"] = seoul_avg_data["품목 이름"].apply(assign_category)

    # 시장별 평균 가격 계산
    avg_price_by_category = (
        near_markets.groupby(["시장/마트 이름", "품목 카테고리"])["가격(원)"]
        .mean()
        .reset_index()
    )

    # 서울시 평균 가격 계산
    seoul_avg_by_category = (
        seoul_avg_data.groupby("품목 카테고리")["가격(원)"]
        .mean()
        .reset_index()
        .rename(columns={"가격(원)": "서울시 평균 가격(원)"})
    )

    # 시장별 데이터와 서울시 평균 데이터 병합
    comparison_data = pd.merge(
        avg_price_by_category,
        seoul_avg_by_category,
        on="품목 카테고리",
        how="left"
    )

    # 서울시 평균과의 차이 계산
    comparison_data["차이(원)"] = comparison_data["서울시 평균 가격(원)"] - comparison_data["가격(원)"]
    comparison_data["차이(%)"] = (
        comparison_data["차이(원)"] / comparison_data["서울시 평균 가격(원)"]
    ) * 100

In [34]:
market_comparison

시장/마트 이름,대림시장,마포농수산물시장,망원시장,백련시장,증산종합시장,차이(원),차이(%)
품목 카테고리,,,,,,,
기타,6809.440559,5126.765531,5236.467066,3012.992032,3757.755708,3796.448528,82.115351
농산물,2617.142857,3222.147059,2709.902913,2713.127451,2988.030612,605.004202,24.435802
생선/해산물,10500.000000,12833.829787,9568.297872,5317.361702,6968.809524,7516.468085,85.568747
생필품,22400.000000,4523.800000,2109.000000,4032.400000,2170.000000,20291.000000,219.258656
음료,NaN,1961.000000,2115.000000,1371.600000,1060.250000,1054.750000,69.734615
인스턴트,2800.000000,2142.448980,1947.916667,1988.571429,867.500000,1932.500000,99.281295
축산물,2928.888889,5092.660000,5117.551020,4370.180000,4019.523810,2188.662132,55.368364

기타 항목은 대림시장, 농산물은 마포농수산물시장, 생선/해산물은 마포농수산물시장, 생필품은 대림시장, 음료는 망원시장, 인스턴트는 대림시장, 축산물은 망원시장이 평균적으로 학교 주변 시장들 중에서 가장 싸다